# -*- coding: utf-8 -*-
"""particle_in_box.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-LxG32kZHWODR3U1dXjzcjcrBkkvrgMB
"""



"""# ♡⁠ Particle In A Box ⊹₊⟡⋆

These notes walk through the particle in a box slowly and visually ♡⁠

# Concept Explained

A particle in a box

## Physical Setup ♡⁠

We consider a particle confined to a one-dimensional box of length \(L\).
The potential is zero inside the box and infinite at the boundaries.
(Include picture here)
"""

import numpy as np
import matplotlib.pyplot as plt

L = 1.0
x = np.linspace(0, L, 500)

def psi(n, x):
    return np.sqrt(2/L) * np.sin(n * np.pi * x / L)

plt.plot(x, psi(1, x))
plt.xlabel("x")
plt.ylabel("ψ(x)")
plt.title("Ground State Wavefunction")
plt.show()